version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_uz_stock
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=admin
      - INFLUXDB_INIT_PASSWORD=adminpass
      - INFLUXDB_INIT_ORG=uzstock
      - INFLUXDB_INIT_BUCKET=historical
    volumes:
      - influxdb_data:/var/lib/influxdb2
volumes:
  influxdb_data:
