module.exports = {
  apps: [
    {
      name: "bitget-bot",
      cwd: "/Users/vitaliyr/dev/bitget-bot",
      script: "bot.py",
      interpreter: "/Users/vitaliyr/dev/bitget-bot/venv/bin/python3",
      max_restarts: 10,
      restart_delay: 5000,
      min_uptime: "10s",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/Users/vitaliyr/dev/bitget-bot/logs/pm2-error.log",
      out_file: "/Users/vitaliyr/dev/bitget-bot/logs/pm2-out.log",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "bitget-dashboard",
      cwd: "/Users/vitaliyr/dev/bitget-bot/dashboard",
      script: "server.js",
      interpreter: "node",
      max_restarts: 5,
      restart_delay: 5000,
    },
    {
      name: "uz-market-bot",
      cwd: "/Users/vitaliyr/dev/uz-market-bot",
      script: "run.py",
      interpreter: "/Users/vitaliyr/dev/uz-market-bot/venv/bin/python3",
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "finanalytics-bot",
      cwd: "/Users/vitaliyr/dev/my-project/finanalytics",
      script: "src/main.py",
      interpreter: "/Users/vitaliyr/dev/my-project/finanalytics/venv/bin/python3",
      args: "--bot",
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/Users/vitaliyr/dev/my-project/finanalytics/logs/pm2-error.log",
      out_file: "/Users/vitaliyr/dev/my-project/finanalytics/logs/pm2-out.log",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "finanalytics-dashboard",
      cwd: "/Users/vitaliyr/dev/my-project/finanalytics",
      script: "src/main.py",
      interpreter: "/Users/vitaliyr/dev/my-project/finanalytics/venv/bin/python3",
      args: "--serve",
      max_restarts: 5,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/Users/vitaliyr/dev/my-project/finanalytics/logs/dash-error.log",
      out_file: "/Users/vitaliyr/dev/my-project/finanalytics/logs/dash-out.log",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "meeting-pipeline",
      cwd: "/Users/vitaliyr/dev/meeting-pipeline",
      script: "meeting_service.py",
      interpreter: "/Users/vitaliyr/dev/meeting-pipeline/venv/bin/python3",
      args: "",
      env: {
        MEETING_SERVICE_PORT: "8001",
        TRANSCRIBE_SERVICE_URL: "http://localhost:8000",
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/tmp/meeting-pipeline-error.log",
      out_file: "/tmp/meeting-pipeline-out.log",
    },
    {
      name: "meeting-watch",
      cwd: "/Users/vitaliyr/dev/meeting-pipeline",
      script: "watch_service.py",
      interpreter: "/Users/vitaliyr/dev/meeting-pipeline/venv/bin/python3",
      args: "--dir /Users/vitaliyr/recordings/ --service http://localhost:8001",
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/tmp/meeting-watch-error.log",
      out_file: "/tmp/meeting-watch-out.log",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "project-dashboard",
      cwd: "/Users/vitaliyr/dev/project-dashboard",
      script: "server.js",
      interpreter: "node",
      max_restarts: 5,
      restart_delay: 5000,
    },
    {
      name: "hermes-webui",
      cwd: "/Users/vitaliyr/dev/hermes-webui",
      script: "server.py",
      interpreter: "/Users/vitaliyr/dev/hermes-webui/venv/bin/python3",
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
    {
      name: "bitget-admin",
      cwd: "/Users/vitaliyr/dev/bitget-bot",
      script: "admin_bot.py",
      interpreter: "/Users/vitaliyr/dev/bitget-bot/venv/bin/python3",
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PYTHONPATH: "",
        PATH: "/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin",
      },
    },
  ],
};