#!/usr/bin/env python3
"""
generate_interview_questions.py — Pre-Task Interview Generator
Generates structured interview questions for complex tasks.

Usage: python3 generate_interview_questions.py <project> <task-description>
"""

import argparse
import sys


TASK_DOMAINS = {
    "trading": {
        "questions": [
            "Какой капитал доступен для этой стратегии?",
            "Какой максимальный DD приемлем?",
            "Нужен ли_human-in-the_loop или полностью автономно?",
            "Какие риски específicos для этой пары/инструмента?",
            "Нужна ли интеграция с существующими защитными механизмами?",
        ],
        "constraints": ["Daily Loss Limit", "Circuit Breaker", "Position Sizing"],
    },
    "infrastructure": {
        "questions": [
            "Какая нагрузка ожидается (RPS, пользователи)?",
            "Нужна ли horizontal scaling?",
            "Какой uptime SLA требуется?",
            "Есть ли legacy constraints?",
            "Нужна ли backward compatibility?",
        ],
        "constraints": ["Zero Downtime", "Data Migration", "Rollback Plan"],
    },
    "feature": {
        "questions": [
            "Какой user story покрываем?",
            "Какие edge cases критичны?",
            "Нужна ли A/B testing инфраструктура?",
            "Какие метрики успеха?",
            "Есть ли dependencies на другие сервисы?",
        ],
        "constraints": ["User Experience", "Performance", "Security"],
    },
}


def generate_questions(project: str, task: str) -> dict:
    """Generate interview questions based on project domain."""
    domain = "feature"
    if "bgt" in project or "trading" in project:
        domain = "trading"
    elif "infra" in project or "server" in project:
        domain = "infrastructure"

    questions = TASK_DOMAINS[domain]["questions"].copy()
    constraints = TASK_DOMAINS[domain]["constraints"].copy()

    return {
        "project": project,
        "task": task,
        "domain": domain,
        "questions": questions,
        "constraints": constraints,
        "output_format": "interview_notes.md",
    }


def main():
    parser = argparse.ArgumentParser(description="Generate interview questions")
    parser.add_argument("project", help="Project directory")
    parser.add_argument("task", help="Task description")
    args = parser.parse_args()

    result = generate_questions(args.project, args.task)

    print(f"# Interview Notes: {result['task']}")
    print(f"\n**Project**: {result['project']}")
    print(f"**Domain**: {result['domain']}")
    print(f"**Date**: {__import__('datetime').datetime.utcnow().strftime('%Y-%m-%d')}")
    print("\n## Questions\n")
    for i, q in enumerate(result["questions"], 1):
        print(f"{i}. {q}")
    print("\n## Constraints\n")
    for c in result["constraints"]:
        print(f"- {c}")
    print("\n## Answers\n")
    print("[Fill during interview]\n")
    print("---\n")
    print(f"Generated by: {__file__}")


if __name__ == "__main__":
    main()
